
sudo: false

language: python

python:
  - 3.5

install:
  - pip install pandas bottle codecov

script:
  - (cd test; PYTHONPATH=../src coverage run -m unittest discover climatechange)

after_success:
  - codecov
