sudo: false

language: python

cache: bundler

python:
  - 3.6

install:
  - pip install pandas bottle matplotlib codecov scipy scikit-learn

script:
  - (cd test; PYTHONPATH=../src coverage run -m unittest discover climatechange)

after_success:
  - (cd test; codecov)

notifications:
  email:
    - mark.royer@maine.edu
    - heather.clifford@maine.edu
